#!/usr/bin/env ruby

# frozen_string_literal: true

require "optparse"
require_relative "lib/log_analyzer"

options = Struct.new(:order, :format, :log_file).new

option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{__FILE__} [OPTIONS]... LOG_FILE_SOURCE"
  opts.separator ""
  opts.separator "Parse the log file given as LOG_FILE_SOURCE."
  opts.separator "The output is the list of WEB page paths with total views counts(option value: TV)"
  opts.separator "Or with unique page views counts(option value: UV)."
  opts.separator "Order results by counts in ascending(opt: ASC) or descending(opt: DESC) order."
  opts.separator ""
  opts.separator "Options:"

  opts.on("-f", "--format FORMAT", "select the output format - TV or UV - default TV") do |format|
    options.format = format
  end

  opts.on("-o", "--order ORDER", "specify results order - default DESC") do |order|
    options.order = order
  end

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end
end

option_parser.parse!

options.log_file = ARGV[0]

unless options.log_file
  puts option_parser
  exit
end

puts
puts LogAnalyzer.report(options)
